remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme  # Add this if you don’t already have a plugins list

title: "My Website Title"
description: "A short description of my site’s purpose"
show_downloads: true  # Optional: Show a download button
