remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme  # add this if you don't already have a plugins list


title: "My Website Title"
description: "A short description of my site’s purpose"
show_downloads: true  # Set to true if you want a download link
