remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme  # Ensure this plugin is enabled

title: "Frederick Kiessling"
description: "University of California, Santa Barbara: Mathematics & Statistics and Data Science (expected to graduate 2026"
show_downloads: true  # This should show download links in your layout
