# _config.yml
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

title: "Frederick Kiessling"
description: "University of California, Santa Barbara"
show_downloads: true

header_pages:
  - index.md
  - about.md
  - projects.md
  - coursework.md
  - cs190n.md
  - story.md
  - Stat_277.md
