remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme  # Ensure this plugin is enabled

title: "TITLE WEBSITE UPDATED"
description: "A short description of my site’s purpose"
show_downloads: true  # This should show download links in your layout
